### ISSUE TITLE
Error running 'dotnet dockerize' : 'Version for package `Brthor.Dockerize.NET` could not be resolved.'

### ISSUE THREAD

**Issue by pieterclaerhout** [brthor/Dockerize.NET#12]
I'm having the same issue as #9  (and I'm running it on a mac using .NET Core 3.1):

<img width="858" alt="Screenshot 2020-01-31 at 16 27 55" src="https://user-images.githubusercontent.com/74731/73551418-a7b0c200-4446-11ea-99d9-66ce30490e7d.png">

Any idea what I might be doing wrong?

**Comment by brthor** [comment]
This tool has not been tested with dotnet core 3.1, but preliminary research shows that it should still work.

To start, I would suggest deleting your bin/obj folders for the project, re-restoring, and testing again if the version cannot be resolved. This will force recreation of nuget's intermediate files, which may be part of the issue.

If that does not work, please provide the output of `dotnet info` and I will try for a repro.

**Comment by pieterclaerhout** [comment]
I got slightly further, but it seems that it's not compatible with .NET Core 3.1 and requires .NET Core 2.0…

<img width="866" alt="Screenshot 2020-02-01 at 10 40 20" src="https://user-images.githubusercontent.com/74731/73590157-7df7a980-44df-11ea-8347-f99f106d7d92.png">

Any chance you can make it compatible with .NET Core 3.1?

**Comment by brthor** [comment]
#13 is tracking compatibility. 

In the meantime, an easy solution is to install the 2.0 framework from the link provided in the error description. Different versions of the framework can exist side-by-side so it should not affect existing projects.
